class.name=Class
method.name=Method
constructor.parameter.name=ConstructorParam
method.parameter.name=MethodParam
static.parameter.name=StaticMethodParam
method.variable.name=MethodVar
enum.name=Enum
enum.constant.name=EnumConstant
enum.method.name=EnumMethod
field.name=field
field.variable.name=fieldVar
